# Generated by Django 3.1.6 on 2021-02-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='M', max_length=5, verbose_name={'F': 'F', 'M': 'M'}),
            preserve_default=False,
        ),
    ]
