# Generated by Django 3.1.6 on 2021-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=5, verbose_name={'Female': 'F', 'Male': 'M'}),
        ),
    ]
