# Generated by Django 3.1.6 on 2021-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210212_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=5, verbose_name={'F': 'Female', 'M': 'Male'}),
        ),
    ]
